login_Ouath 네이버&카카오
earning-rightly/level-up-test pull request #3
Opened 2023-03-23 02:20 UTC by hihibara

네이버 카카오 Ouath 로그인을 만들었습니다. 
네이버는 login.html과 callback.html 2개에 나눠서 만들었습니다. (데모가 있어서 가져와서 사용했습니다.) 네이버 로그아웃은 
카카오는 loginhtml안에서 구현했습니다. (마찬가지로 데모가 있어서 가져왔습니다)
로그아웃 기능까지 만들기는 했는데 네이버 로그아웃은 callback.htm 에 "https://nid.naver.com/nidlogin.logout"링크를 통해서
구현했는데 토큰을 없에서 하는 것이 아니라서 그런지 chrome 전체에서  네이버가 로그아웃됩니다. 
카카오는 현재 페이지에서만 로그아웃이 되는데 네이버로그인 처럼 새로운 창을 띄우고 싶은데 그것이 안되서 어떻게 가야 할지
여쭤보고 싶습니다.

2023-03-23 08:41 UTC, Enoch-Kim commented
@hihibara 세부 내용 markdown 형식 적용됩니다. markdown에 대해 알아보시고 가독성 있게 구성해주세요 :)

2023-03-23 09:32 UTC, Enoch-Kim requested changes
잘하고 있지만.. 조금 더 많이 분발합시다^^

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +        const secret = "MaLARH3T4B";
우선 script를 별도로 js 파일에 두고 사용했으면 좋겠습니다. 그리고 id, secret 처럼 단순한 이름보다 naverOauthId / naverOauthSecret 처럼 명확한 네이밍 부탁드려요 :)

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +          // );
이런 불필요한 주석은 기본적으로 지워주세요

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +    <script type="text/javascript">
스크립트 파일들은 js 파일로 관리하고 html에서 해당 파일 불러서 사용했으면 좋겠습니다.

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +    ></script>
이렇게 내부에 아무것도 없는 경우 다음처럼 쓸 수 있습니다.
```suggestion
    <script
      type="text/javascript"
      src="https://static.nid.naver.com/js/naverLogin_implicit-1.0.3.js"
      charset="utf-8"
    />
```

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +      naver_id_login.get_naver_userprofile("naverSignInCallback()");
아무 행동도 하지 않았는데 왜 alert와 함수를 실행하는 것일까요? script 태그에 대해 더 공부할 필요가 있어보입니다.

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/CallBack.html
> +<!-- //https://nid.naver.com/oauth2.0/token?grant_type=delete&client_id=jyvqXeaVOVmV&client_secret=527300A0_COq1_XV33cf&access_token=c8ceMEJisO4Se7uGCEYKK1p52L93bHXLnaoETis9YzjfnorlQwEisqemfpKHUq2gY&
불필요한 주석 제거해주세요.

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.html
> +            </a> -->
제거

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.html
> +              <!-- <span>카카오 로그아웃</span> -->
제거

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.html
> +      </a> -->
제거

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.js
> +console.log(Kakao.isInitialized()); // sdk초기화여부판단
이걸 콘솔로 출력하는 것보다 initialize가 안됐을 시 실행하지 않는쪽으로 코드를 작성하면 좋겠죠?
```suggestion
if(!Kakao.isInitialized()) {
  alert('kakao sdk is not initialized')
  return
}
```

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.js
> +function kakaoLogin() {
전 다음과 같이 나옵니다. 확인해주세요. (아마 로컬 피씨 아이피를 등록한 것 같은데 맞나요?)
![스크린샷 2023-03-23 오후 6 30 06](https://user-images.githubusercontent.com/60127664/227160802-55179e5d-94cb-41b1-b40c-b76854fee76a.png)

2023-03-23 09:32 UTC, Enoch-Kim commented on apps/web-login/Login.js
> +          openNew(); // 세로운 창을 띄우고 싶은데 왜 안되는 걸까요? 알려 주세요
여기까지 진행이 안돼서 모르겠네요,,,

2023-03-24 02:55 UTC, hihibara commented on apps/web-login/CallBack.html
> +        "http://192.168.0.12:8887/Login.html#"
`onst WEB_IP = new URL(document.location.href);
const pathname = WEB_IP.pathname; // url-path 부분
const CALLBACK_IP =
  WEB_IP.origin + // scheme와 hosts 부분
  pathname.substring(0, pathname.lastIndexOf("/")) +
  "/CallBack.html";`

2023-03-24 02:56 UTC, hihibara commented on apps/web-login/CallBack.html
> +        "http://192.168.0.12:8887/Login.html#"
`const WEB_IP = new URL(document.location.href);
const pathname = WEB_IP.pathname; // url-path 부분
const CALLBACK_IP =
  WEB_IP.origin + // scheme와 hosts 부분
  pathname.substring(0, pathname.lastIndexOf("/")) +
  "/CallBack.html";
const CLIENT_ID = "Hw7RwBFOB7UjSufSEEjy";`

2023-03-24 02:57 UTC, hihibara commented on apps/web-login/CallBack.html
> +        "http://192.168.0.12:8887/Login.html#"
`const WEB_IP = new URL(document.location.href);
const pathname = WEB_IP.pathname; // url-path 부분
const CALLBACK_IP =
  WEB_IP.origin + // scheme와 hosts 부분
  pathname.substring(0, pathname.lastIndexOf("/")) +
  "/CallBack.html";
const CLIENT_ID = "Hw7RwBFOB7UjSufSEEjy";`

로 수정했습니다

2023-03-24 03:00 UTC, hihibara commented on apps/web-login/CallBack.html
> +        "http://192.168.0.12:8887/Login.html#"
`const WEB_IP = new URL(document.location.href);

const pathname = WEB_IP.pathname; // url-path 부분

const CALLBACK_IP =
  WEB_IP.origin + // scheme와 hosts 부분
  pathname.substring(0, pathname.lastIndexOf("/")) +
```suggestion
        "http://192.168.0.12:8887/Login.html#"
```
  "/CallBack.html";

const CLIENT_ID = "Hw7RwBFOB7UjSufSEEjy";`

2023-03-24 03:01 UTC, hihibara commented on apps/web-login/CallBack.html
> +        "http://192.168.0.12:8887/Login.html#"
```suggestion
        const WEB_IP = new URL(document.location.href);
const pathname = WEB_IP.pathname; // url-path 부분
const CALLBACK_IP =
  WEB_IP.origin + // scheme와 hosts 부분
  pathname.substring(0, pathname.lastIndexOf("/")) +
  "/CallBack.html";
```

상대 url로 수정했습니다. 괜찮나요?

2023-03-24 16:23 UTC, merged